Repository 3scale-sre/saas-operator, pull requests merged in 2020-07, with the labels that each got.

#10 Update zync-que dashboard
  Makefile
  roles/zync/templates/zync-grafanadashboard.yaml
Labels: enhancement

#13 Feature/Small general improvements
  deploy/crds/saas.3scale.net_autossls_crd.yaml
  deploy/crds/saas.3scale.net_backends_crd.yaml
  deploy/crds/saas.3scale.net_zyncs_crd.yaml
  roles/autossl/tasks/main.yml
  roles/autossl/templates/autossl-grafanadashboard.yaml
  roles/backend/tasks/main.yml
  roles/zync/tasks/main.yml
Labels: enhancement

#12 Feature/Add CORSProxy controller
  Makefile
  README.md
  deploy/crds/saas.3scale.net_corsproxies_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_corsproxy_cr.yaml
  deploy/role.yaml
  docs/corsproxy-crd-reference.md
  roles/corsproxy/defaults/main.yml
  roles/corsproxy/meta/main.yml
  roles/corsproxy/tasks/main.yml
  roles/corsproxy/templates/cors-proxy-deployment.yaml
  roles/corsproxy/templates/cors-proxy-grafanadashboard.yaml
  roles/corsproxy/templates/cors-proxy-ingress.yaml
  roles/corsproxy/templates/cors-proxy-podmonitor.yaml
  roles/corsproxy/templates/cors-proxy-service.yaml
  roles/corsproxy/templates/cors-proxy-system-database-secretdefinition.yaml
  watches.yaml
Labels: enhancement

#16 Feature/Add echoapi controller
  Makefile
  README.md
  deploy/crds/saas.3scale.net_echoapis_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_echoapi_cr.yaml
  docs/echoapi-crd-reference.md
  roles/echoapi/defaults/main.yml
  roles/echoapi/meta/main.yml
  roles/echoapi/tasks/main.yml
  roles/echoapi/templates/echo-api-deployment.yaml
  roles/echoapi/templates/echo-api-podmonitor.yaml
  roles/echoapi/templates/echo-api-service.yaml
  watches.yaml
Labels: enhancement

#18 Remove autossl possibility to configure s3 logging at AWS ELB
  Makefile
  deploy/crds/saas.3scale.net_autossls_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_autossl_cr.yaml
  docs/autossl-crd-reference.md
  roles/autossl/templates/autossl-service.yaml
Labels: enhancement

#19 Feature/Add marin3r to backend controller
  Makefile
  deploy/crds/saas.3scale.net_backends_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_backend_cr.yaml
  deploy/role.yaml
  docs/backend-crd-reference.md
  roles/backend/defaults/main.yml
  roles/backend/tasks/main.yml
  roles/backend/templates/backend-listener-deployment.yaml
  roles/backend/templates/backend-listener-podmonitor.yaml
  roles/backend/templates/backend-listener-service.yaml
  roles/backend/templates/backend-route.yaml
Labels: enhancement

#20 controller/apicast
  Makefile
  README.md
  deploy/crds/saas.3scale.net_apicasts_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_apicast_cr.yaml
  docs/apicast-crd-reference.md
  roles/apicast/defaults/main.yml
  roles/apicast/meta/main.yml
  roles/apicast/tasks/main.yml
  roles/apicast/templates/apicast-deployment.yaml
  roles/apicast/templates/apicast-gateway-service.yaml
  roles/apicast/templates/apicast-grafanadashboard.yaml
  roles/apicast/templates/apicast-management-service.yaml
  roles/apicast/templates/apicast-podmonitor.yaml
  roles/apicast/templates/apicast-services-grafanadashboard.yaml
  watches.yaml
Labels: documentation, enhancement

#22 Add MappingService controller
  README.md
  deploy/crds/saas.3scale.net_mappingservice_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_mappingservice_cr.yaml
  docs/mappingservice-crd-reference.md
  roles/mappingservice/defaults/main.yml
  roles/mappingservice/meta/main.yml
  roles/mappingservice/tasks/main.yml
  roles/mappingservice/templates/mappingservice-deployment.yaml
  roles/mappingservice/templates/mappingservice-grafanadashboard.yaml
  roles/mappingservice/templates/mappingservice-podmonitor.yaml
  roles/mappingservice/templates/mappingservice-service.yaml
  roles/mappingservice/templates/mappingservice-system-master-access-token-secretdefinition.yaml
  watches.yaml
Labels: documentation, enhancement

#23 feat: add cluster role aggregations
  deploy/clusterrole-aggregations/saas.3scale.net_apicasts.yaml
  deploy/clusterrole-aggregations/saas.3scale.net_autossls.yaml
  deploy/clusterrole-aggregations/saas.3scale.net_backends.yaml
  deploy/clusterrole-aggregations/saas.3scale.net_corsproxies.yaml
  deploy/clusterrole-aggregations/saas.3scale.net_echoapis.yaml
  deploy/clusterrole-aggregations/saas.3scale.net_mappingservice.yaml
  deploy/clusterrole-aggregations/saas.3scale.net_zyncs.yaml
Labels: enhancement

#24 Fix: Use plural for mappingservices
  deploy/clusterrole-aggregations/saas.3scale.net_mappingservices.yaml
  deploy/crds/saas.3scale.net_mappingservices_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_mappingservices_cr.yaml
Labels: enhancement

#26 Use plural in mappingservices cluster role aggregation
  deploy/clusterrole-aggregations/saas.3scale.net_mappingservices.yaml
Labels: bug

#25 fix: Remove wildcard from saas.3scale.net role rule
  deploy/role.yaml
Labels: enhancement

#27 bug/uncomment-watches
  deploy/role.yaml
  watches.yaml
Labels: bug

#28 Add the crds' status subresources to the operator role
  deploy/role.yaml
Labels: bug

#29 Feature/Add HA to backend controller
  Makefile
  deploy/crds/saas.3scale.net_backends_crd.yaml
  docs/backend-crd-reference.md
  roles/backend/defaults/main.yml
  roles/backend/tasks/main.yml
  roles/backend/templates/backend-listener-deployment.yaml
  roles/backend/templates/backend-listener-hpa.yaml
  roles/backend/templates/backend-listener-internal-service.yaml
  roles/backend/templates/backend-listener-pdb.yaml
  roles/backend/templates/backend-worker-deployment.yaml
  roles/backend/templates/backend-worker-hpa.yaml
  roles/backend/templates/backend-worker-pdb.yaml
Labels: enhancement

#31 Feature/Update marin3r annotations config on EchoAPI controller
  deploy/crds/saas.3scale.net_echoapis_crd.yaml
  deploy/crds/saas.3scale.net_v1alpha1_echoapi_cr.yaml
  docs/echoapi-crd-reference.md
  roles/echoapi/tasks/main.yml
  roles/echoapi/templates/echo-api-deployment.yaml
  roles/echoapi/templates/echo-api-podmonitor.yaml
Labels: enhancement

#32 Add PDB/HPA rbac permissions to operator role
  deploy/role.yaml
Labels: bug

#34 Feature/Add HA to Apicast controller
  deploy/crds/saas.3scale.net_apicasts_crd.yaml
  docs/apicast-crd-reference.md
  roles/apicast/defaults/main.yml
  roles/apicast/tasks/main.yml
  roles/apicast/templates/apicast-deployment.yaml
  roles/apicast/templates/apicast-hpa.yaml
  roles/apicast/templates/apicast-pdb.yaml
Labels: enhancement

#35 Add regex validation to Backend CRD PDB fields
  deploy/crds/saas.3scale.net_backends_crd.yaml
Labels: enhancement
