Repository 3scale-sre/saas-operator, pull requests merged in 2021-09, with the labels that each got.

#119 Feat/Add optional System assets CDN field to System controller
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  controllers/system_controller_suite_test.go
  docs/api-reference/reference.asciidoc
  pkg/assets/bindata.go
  pkg/generators/system/config/options.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#120 Soft-deprecation of System redis message bus DSN field and associate ENV VARS
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  controllers/system_controller_suite_test.go
  docs/api-reference/reference.asciidoc
  pkg/assets/bindata.go
  pkg/generators/system/config/options.go
  pkg/generators/system/config/sphinx_options.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#121 Feat/Simplify System CRD
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/samples/saas_v1alpha1_system.yaml
  controllers/system_controller.go
  controllers/system_controller_suite_test.go
  docs/api-reference/reference.asciidoc
  pkg/assets/bindata.go
  pkg/generators/system/config/options.go
  pkg/generators/system/generator.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#122 fix/service-reconcile-loop
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/assets/bindata.go
  pkg/basereconciler/reconcile_resources.go
  pkg/generators/common_blocks/service/util.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/S, lgtm, approved

#123 Feat/Hard-deprecation of System seed and metrics custom resource fields
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  docs/api-reference/reference.asciidoc
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/L, lgtm, approved
