Repository 3scale-sre/saas-operator, pull requests merged in 2021-06, with the labels that each got.

#106 fix: split sphinx address config
  .vscode/launch.json
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/generators/system/config/options.go
  pkg/generators/system/config/static.go
  pkg/generators/system/sphinx_service.go
  pkg/version/version.go
Labels: approved, kind/bug, kind/feature, lgtm, priority/important-soon, size/S

#108 fix: deployment replicas defaulting
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  go.mod
  go.sum
  pkg/basereconciler/reconcile_resources.go
  pkg/version/version.go
Labels: approved, kind/bug, lgtm, priority/important-soon, size/S

#109 Add documentation about the operator release process
  Makefile
  docs/release.md
Labels: approved, kind/documentation, lgtm, priority/important-soon, size/S

#110 feat/customizable-affinity
  Makefile
  api/v1alpha1/apicast_types.go
  api/v1alpha1/autossl_types.go
  api/v1alpha1/backend_types.go
  api/v1alpha1/corsproxy_types.go
  api/v1alpha1/echoapi_types.go
  api/v1alpha1/mappingservice_types.go
  api/v1alpha1/system_types.go
  api/v1alpha1/zync_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_autossls.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_corsproxies.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_mappingservices.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  config/crd/bases/saas.3scale.net_apicasts.yaml
  config/crd/bases/saas.3scale.net_autossls.yaml
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_corsproxies.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_mappingservices.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_zyncs.yaml
  config/manager/kustomization.yaml
  pkg/generators/apicast/deployment.go
  pkg/generators/autossl/deployment.go
  pkg/generators/backend/cron_deployment.go
  pkg/generators/backend/listener_deployment.go
  pkg/generators/backend/worker_deployment.go
  pkg/generators/common_blocks/pod/util.go
  pkg/generators/corsproxy/deployment.go
  pkg/generators/echoapi/deployment.go
  pkg/generators/mappingservice/deployment.go
  pkg/generators/system/app_deployment.go
  pkg/generators/system/sidekiq_deployment.go
  pkg/generators/system/sphinx_statefulset.go
  pkg/generators/zync/api_deployment.go
  pkg/generators/zync/que_deployment.go
  pkg/version/version.go
Labels: approved, kind/feature, lgtm, priority/important-soon, size/XL

#111 feat: rename apicast token name
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  controllers/system_controller_suite_test.go
  pkg/assets/bindata.go
  pkg/generators/system/config/options.go
  pkg/version/version.go
Labels: approved, kind/cleanup, lgtm, priority/important-soon, size/M

#112 feat: provide a deprecation path for the apicastAccessToken
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  pkg/version/version.go
Labels: approved, kind/feature, lgtm, priority/important-soon, size/M

#113 feat: deprecate apicastAccessToken attribute
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  pkg/version/version.go
Labels: approved, kind/feature, lgtm, priority/important-soon, size/M
