Repository 3scale-sre/saas-operator, pull requests merged in 2021-11, with the labels that each got.

#132 feat/upgrade-operator-sdk
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Makefile
  PROJECT
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/saas-operator-controller-manager_v1_serviceaccount.yaml
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_autossls.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_corsproxies.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_mappingservices.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/saas.3scale.net_apicasts.yaml
  config/crd/bases/saas.3scale.net_autossls.yaml
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_corsproxies.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_mappingservices.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_zyncs.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/service_account.yaml
  docs/api-reference/reference.asciidoc
  go.mod
  go.sum
  pkg/apis/grafana/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/secrets-manager/v1alpha1/zz_generated.deepcopy.go
  pkg/assets/bindata.go
  pkg/basereconciler/test/api/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, priority/important-soon, size/XL, lgtm, approved

#131 Change tpl extension to gtpl for go templates
  pkg/assets/bindata.go
  pkg/assets/dashboards/apicast-services.json.gtpl
  pkg/assets/dashboards/apicast.json.gtpl
  pkg/assets/dashboards/autossl.json.gtpl
  pkg/assets/dashboards/backend.json.gtpl
  pkg/assets/dashboards/cors-proxy.json.gtpl
  pkg/assets/dashboards/mapping-service.json.gtpl
  pkg/assets/dashboards/system.json.gtpl
  pkg/assets/dashboards/zync.json.gtpl
  pkg/generators/apicast/generator.go
  pkg/generators/autossl/generator.go
  pkg/generators/backend/generator.go
  pkg/generators/corsproxy/generator.go
  pkg/generators/mappingservice/generator.go
  pkg/generators/system/generator.go
  pkg/generators/zync/generator.go
Labels: kind/feature, priority/backlog, size/M, lgtm, approved

#133 Update system-sidekiq-low deployment to manage new mailers queue
  api/v1alpha1/system_types.go
  controllers/system_controller_suite_test.go
Labels: kind/feature, priority/important-soon, size/XS, lgtm, approved

#134 feat/disable-metrics-auth-proxy
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_autossls.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_corsproxies.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_mappingservices.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  bundle/metadata/annotations.yaml
  config/default/custom/manager_patch.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/kustomization.yaml
  config/test/kustomization.yaml
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#135 feat/sidekiq-boxy-failover
  Dockerfile
  Makefile
  api/v1alpha1/common_types.go
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/saas.3scale.net_apicasts.yaml
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  docs/api-reference/reference.asciidoc
  go.mod
  go.sum
  pkg/basereconciler/reconciler.go
  pkg/generators/common_blocks/marin3r/util.go
  pkg/generators/common_blocks/marin3r/util_test.go
  pkg/generators/system/sidekiq_deployment.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/L, lgtm, approved

#136 feat/upgrade-controller-runtime
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  go.mod
  go.sum
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved
