Repository 3scale-sre/saas-operator, pull requests merged in 2021-07, with the labels that each got.

#115 Fix: Update zync dashboard job label
  Makefile
  config/manager/kustomization.yaml
  pkg/assets/bindata.go
  pkg/assets/dashboards/zync.json.tpl
Labels: approved, kind/bug, lgtm, priority/important-longterm, size/S

#116 fix: bump csv version to 0.10.2
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  pkg/version/version.go
Labels: approved, kind/bug, lgtm, priority/important-soon, size/S

#117 feat: Sphinx custom image
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  pkg/generators/system/generator.go
  pkg/version/version.go
Labels: approved, kind/feature, lgtm, priority/important-longterm, size/M

#118 fix/backend-hpa
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  controllers/backend_controller.go
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: approved, kind/bug, lgtm, priority/critical-urgent, size/S
