Repository 3scale-sre/saas-operator, pull requests merged in 2021-03, with the labels that each got.

#81 Update default backend-cron memory resources after switch docker base image to ubi8
  api/v1alpha1/backend_types.go
Labels: kind/feature, priority/important-soon

#80 feat/actions/test-workflow
  .github/workflows/test.yaml
  Makefile
Labels: kind/feature, priority/important-soon, size/S

#82 Update the badge with the new test workflow
  README.md
Labels: kind/documentation, priority/backlog, size/XS

#85 feat/actions/release
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  go.mod
  hack/new-release.sh
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M

#84 Feat/Update grafana dashboards
  docs/development.md
  pkg/assets/bindata.go
  pkg/assets/dashboards/apicast-services.json.tpl
  pkg/assets/dashboards/apicast.json.tpl
  pkg/assets/dashboards/autossl.json.tpl
  pkg/assets/dashboards/backend.json.tpl
  pkg/assets/dashboards/cors-proxy.json.tpl
  pkg/assets/dashboards/mapping-service.json.tpl
  pkg/assets/dashboards/zync.json.tpl
Labels: kind/bug, kind/feature

#88 Release/v0.9.1
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: kind/feature, priority/important-soon

#89 Add listener internal metrics panels to backend grafana dashboard
  pkg/assets/bindata.go
  pkg/assets/dashboards/backend.json.tpl
Labels: kind/feature

#91 Feat/Add system grafana dashboard
  README.md
  controllers/system_controller.go
  controllers/system_controller_suite_test.go
  pkg/assets/bindata.go
  pkg/assets/dashboards/system.json.tpl
  pkg/generators/system/generator.go
Labels: kind/feature

#92 Release/v0.9.2
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: kind/feature, priority/important-soon

#93 Downgrade prometheus-operator API to v0.42
  go.mod
  go.sum
Labels: kind/bug, priority/critical-urgent, size/S

#94 release/v0.9.3
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/critical-urgent, size/XS

#95 fix/marin3r-annotations
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/basereconciler/reconcile_resources.go
  pkg/basereconciler/test/api/v1alpha1/example.com_tests.yaml
  pkg/basereconciler/test/api/v1alpha1/test_types.go
  pkg/basereconciler/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/basereconciler/test/test_controller.go
  pkg/basereconciler/test/test_controller_suite_test.go
  pkg/version/version.go
Labels: kind/bug, priority/critical-urgent, size/S

#96 Fix NLB Service annotations by setting needed aws-load-balancer-type annotation
  pkg/generators/common_blocks/service/util.go
Labels: kind/bug, priority/critical-urgent

#97 Add missing SecretKeyBase envvar to Zync deployments
  pkg/generators/zync/config/api_options.go
  pkg/generators/zync/config/que_options.go
Labels: kind/bug, priority/critical-urgent, size/XS

#98 Release 0.9.5
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/XS

#100 Add OWNERS file
  OWNERS
Labels: approved, lgtm
