Repository 3scale-sre/saas-operator, pull requests merged in 2021-02, with the labels that each got.

#62 feat/doc
  LICENSE
  Makefile
  README.md
  docs/api-reference/config.yaml
  docs/api-reference/reference.asciidoc
  docs/api-reference/templates/asciidoctor/gv_details.tpl
  docs/api-reference/templates/asciidoctor/gv_list.tpl
  docs/api-reference/templates/asciidoctor/type.tpl
  docs/api-reference/templates/asciidoctor/type_members.tpl
  docs/development.md
  docs/getting-started.md
  docs/logos/3scale-saas-logo-60px.png
  docs/logos/3scale-saas-logo.png
  docs/logos/3scale-saas-logo.svg
  docs/release.md
Labels: kind/documentation, priority/important-soon, size/XS

#64 Fix mapping-service grafana dashboard
  pkg/assets/bindata.go
  pkg/assets/dashboards/mapping-service.json.tpl
Labels: kind/bug, priority/important-soon

#63 feat/config-improvements
  go.mod
  go.sum
  pkg/generators/apicast/config/config.go
  pkg/generators/apicast/deployment.go
  pkg/generators/autossl/config/config.go
  pkg/generators/autossl/deployment.go
  pkg/generators/common_blocks/pod/environment.go
  pkg/generators/common_blocks/pod/environment_test.go
  pkg/generators/common_blocks/secrets/secretdefinition.go
  pkg/generators/common_blocks/secrets/secretdefinition_test.go
  pkg/generators/common_blocks/secrets/util.go
  pkg/generators/corsproxy/config/config.go
  pkg/generators/corsproxy/deployment.go
  pkg/generators/corsproxy/generator.go
  pkg/generators/mappingservice/config/config.go
  pkg/generators/mappingservice/deployment.go
  pkg/generators/mappingservice/generator.go
Labels: kind/feature, priority/critical-urgent, size/L

#65 Ignore unset values in Deployment spec for reconcile diff
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/corsproxy_controller.go
  controllers/mappingservice_controller.go
  pkg/basereconciler/reconciler.go
  pkg/generators/apicast/deployment.go
  pkg/generators/autossl/deployment.go
  pkg/generators/corsproxy/deployment.go
Labels: kind/feature, priority/important-longterm, size/XS

#66 Fix/reconcile-services
  controllers/autossl_controller_suite_test.go
  pkg/basereconciler/reconciler.go
Labels: kind/bug, priority/critical-urgent, size/S

#67 Fix the secretdefinition generator
  pkg/generators/common_blocks/secrets/secretdefinition.go
  pkg/generators/common_blocks/secrets/secretdefinition_test.go
Labels: kind/bug, priority/critical-urgent, size/XS

#68 Feat/Add Backend go controller
  PROJECT
  README.md
  api/v1alpha1/backend_types.go
  api/v1alpha1/common_types.go
  api/v1alpha1/common_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_backends.yaml
  config/crd/patches/webhook_in_backends.yaml
  config/rbac/backend_editor_role.yaml
  config/rbac/backend_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/saas_v1alpha1_backend.yaml
  controllers/backend_controller.go
  controllers/backend_controller_suite_test.go
  controllers/suite_test.go
  docs/api-reference/reference.asciidoc
  main.go
  pkg/assets/bindata.go
  pkg/assets/dashboards/backend.json.tpl
  pkg/generators/backend/config/config.go
  pkg/generators/backend/cron_deployment.go
  pkg/generators/backend/generator.go
  pkg/generators/backend/listener_deployment.go
  pkg/generators/backend/services.go
  pkg/generators/backend/worker_deployment.go
  pkg/generators/common_blocks/service/util.go
Labels: kind/feature, priority/important-soon

#70 Fix custom resource deletion
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/mappingservice_controller.go
  pkg/basereconciler/reconciler.go
  pkg/basereconciler/test/test_controller.go
Labels: kind/bug, priority/important-soon

#73 Implement new config generator for all controllers
  pkg/generators/apicast/config/config.go
  pkg/generators/apicast/config/options.go
  pkg/generators/apicast/deployment.go
  pkg/generators/apicast/generator.go
  pkg/generators/autossl/config/config.go
  pkg/generators/autossl/config/options.go
  pkg/generators/autossl/deployment.go
  pkg/generators/autossl/generator.go
  pkg/generators/backend/config/config.go
  pkg/generators/backend/config/cron_options.go
  pkg/generators/backend/config/listener_options.go
  pkg/generators/backend/config/worker_options.go
  pkg/generators/backend/cron_deployment.go
  pkg/generators/backend/generator.go
  pkg/generators/backend/listener_deployment.go
  pkg/generators/backend/worker_deployment.go
  pkg/generators/common_blocks/pod/environment.go
  pkg/generators/common_blocks/pod/environment_test.go
  pkg/generators/common_blocks/pod/new_environment.go
  pkg/generators/common_blocks/pod/new_environment_test.go
  pkg/generators/common_blocks/pod/secretdefinitions.go
  pkg/generators/common_blocks/pod/secretdefinitions_test.go
  pkg/generators/common_blocks/secrets/secretdefinition.go
  pkg/generators/common_blocks/secrets/secretdefinition_test.go
  pkg/generators/corsproxy/config/config.go
  pkg/generators/corsproxy/config/options.go
  pkg/generators/corsproxy/deployment.go
  pkg/generators/corsproxy/generator.go
  pkg/generators/mappingservice/config/config.go
  pkg/generators/mappingservice/config/options.go
  pkg/generators/mappingservice/deployment.go
  pkg/generators/mappingservice/generator.go
Labels: kind/feature, priority/important-soon, size/M

#75 Fix backend-listener container args
  pkg/generators/backend/listener_deployment.go
Labels: kind/bug, priority/important-soon

#74 feat/Add zync go controller
  PROJECT
  README.md
  api/v1alpha1/common_types.go
  api/v1alpha1/system_types.go
  api/v1alpha1/zync_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/saas.3scale.net_zyncs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_zyncs.yaml
  config/crd/patches/webhook_in_zyncs.yaml
  config/rbac/role.yaml
  config/rbac/zync_editor_role.yaml
  config/rbac/zync_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/saas_v1alpha1_zync.yaml
  controllers/suite_test.go
  controllers/zync_controller.go
  controllers/zync_controller_suite_test.go
  docs/api-reference/reference.asciidoc
  main.go
  pkg/assets/bindata.go
  pkg/assets/dashboards/zync.json.tpl
  pkg/generators/system/config/options.go
  pkg/generators/zync/api_deployment.go
  pkg/generators/zync/config/api_options.go
  pkg/generators/zync/config/que_options.go
  pkg/generators/zync/generator.go
  pkg/generators/zync/que_deployment.go
  pkg/generators/zync/services.go
Labels: kind/feature, priority/important-soon

#76 Fix errors in WorkerOptions
  pkg/generators/backend/config/worker_options.go
Labels: kind/bug, priority/important-soon, size/XS

#77 Fix zync-que container command with missing single quote
  pkg/generators/zync/que_deployment.go
Labels: kind/bug

#78 Feat: EchoAPI Go based controller
  PROJECT
  README.md
  api/v1alpha1/echoapi_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_echoapis.yaml
  config/crd/patches/webhook_in_echoapis.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/rbac/echoapis_editor_role.yaml
  config/rbac/echoapis_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomization.yaml
  config/samples/saas_v1alpha1_echoapi.yaml
  controllers/echoapi_controller.go
  controllers/echoapi_controller_suite_test.go
  controllers/suite_test.go
  docs/api-reference/reference.asciidoc
  main.go
  pkg/assets/bindata.go
  pkg/generators/echoapi/deployment.go
  pkg/generators/echoapi/generator.go
  pkg/generators/echoapi/service.go
Labels: kind/feature, priority/important-soon, size/M

#79 feat/stable-channel
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M
