Repository 3scale-sre/saas-operator, pull requests merged in 2022-10, with the labels that each got.

#222 fix: Update cpu metrics rule
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/assets/bindata.go
  pkg/assets/dashboards/apicast.json.gtpl
  pkg/assets/dashboards/autossl.json.gtpl
  pkg/assets/dashboards/backend.json.gtpl
  pkg/assets/dashboards/cors-proxy.json.gtpl
  pkg/assets/dashboards/mapping-service.json.gtpl
  pkg/assets/dashboards/redis-sentinel.json.gtpl
  pkg/assets/dashboards/system.json.gtpl
  pkg/assets/dashboards/twemproxy.json.gtpl
  pkg/assets/dashboards/zync.json.gtpl
  pkg/version/version.go
Labels: kind/bug, kind/feature, priority/important-soon, size/M, lgtm, approved

#223 release: v0.16.3
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/S, size/XS, lgtm, approved, kind/release

#224 feat/resource-reconcilers
  pkg/reconcilers/basereconciler/v2/resources/configmap.go
  pkg/reconcilers/basereconciler/v2/resources/external_secret.go
  pkg/reconcilers/basereconciler/v2/resources/grafana_dashboard.go
  pkg/reconcilers/basereconciler/v2/resources/hpa.go
  pkg/reconcilers/basereconciler/v2/resources/pdb.go
  pkg/reconcilers/basereconciler/v2/resources/pod_monitor.go
  pkg/reconcilers/basereconciler/v2/resources/services.go
  pkg/reconcilers/basereconciler/v2/resources/simple_resources.go
  pkg/resource_builders/grafanadashboard/resource.go
Labels: kind/feature, priority/important-longterm, size/M, lgtm, approved
