Repository 3scale-sre/saas-operator, pull requests merged in 2022-11, with the labels that each got.

#226 fix/controller-watches
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/redisshard_controller.go
  controllers/sentinel_controller.go
  controllers/system_controller.go
  controllers/twemproxyconfig_controller.go
  controllers/zync_controller.go
  pkg/generators/sentinel/generator.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/M, lgtm, approved

#229 Feat/Update System API
  Makefile
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/samples/saas_v1alpha1_system.yaml
  controllers/system_controller_suite_test.go
  docs/api-reference/reference.asciidoc
  pkg/generators/system/config/options.go
  pkg/generators/system/config/sphinx_options.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#230 Feat/Fix reconciler diff on Deployment/Statefulset generators
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/generators/apicast/deployment.go
  pkg/generators/autossl/deployment.go
  pkg/generators/backend/cron_deployment.go
  pkg/generators/backend/listener_deployment.go
  pkg/generators/backend/worker_deployment.go
  pkg/generators/corsproxy/deployment.go
  pkg/generators/echoapi/deployment.go
  pkg/generators/mappingservice/deployment.go
  pkg/generators/sentinel/statefulset.go
  pkg/generators/system/app_deployment.go
  pkg/generators/system/console_statefulset.go
  pkg/generators/system/sidekiq_deployment.go
  pkg/generators/zync/api_deployment.go
  pkg/generators/zync/que_deployment.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/M, lgtm, approved

#232 Fix/System-console statefulset args
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/generators/system/console_statefulset.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/S, lgtm, approved

#231 Drop usage of lockedresource reconciler from operator-utils
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_autossls.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_corsproxies.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_mappingservices.yaml
  bundle/manifests/saas.3scale.net_redisshards.yaml
  bundle/manifests/saas.3scale.net_sentinels.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_twemproxyconfigs.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  config/crd/bases/saas.3scale.net_apicasts.yaml
  config/crd/bases/saas.3scale.net_autossls.yaml
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_corsproxies.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_mappingservices.yaml
  config/crd/bases/saas.3scale.net_redisshards.yaml
  config/crd/bases/saas.3scale.net_sentinels.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_twemproxyconfigs.yaml
  config/crd/bases/saas.3scale.net_zyncs.yaml
  config/manager/kustomization.yaml
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/backend_controller_suite_test.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/redisshard_controller.go
  controllers/sentinel_controller.go
  controllers/suite_test.go
  controllers/system_controller.go
  controllers/system_controller_suite_test.go
  controllers/twemproxyconfig_controller.go
  controllers/zync_controller.go
  go.mod
  go.sum
  main.go
  pkg/assets/bindata.go
  pkg/reconcilers/basereconciler/v2/reconciler.go
  pkg/reconcilers/basereconciler/v2/resources/services.go
  pkg/reconcilers/basereconciler/v2/test/suite_test.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
  pkg/reconcilers/workloads/deployment_based_workload.go
  pkg/reconcilers/workloads/test/suite_test.go
  pkg/reconcilers/workloads/test/test_controller.go
  pkg/reconcilers/workloads/test/test_controller_suite_test.go
  pkg/version/version.go
Labels: kind/cleanup, priority/important-longterm, size/L, lgtm, approved

#233 Feat/Add System/Zync optional bugsnag releaseStage
  Makefile
  api/v1alpha1/common_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_zyncs.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/samples/saas_v1alpha1_system.yaml
  config/samples/saas_v1alpha1_zync.yaml
  controllers/system_controller_suite_test.go
  controllers/zync_controller_suite_test.go
  docs/api-reference/reference.asciidoc
  pkg/generators/system/config/options.go
  pkg/generators/zync/config/api_options.go
  pkg/generators/zync/config/que_options.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#234 Stable release v0.17.1
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/S, lgtm, approved, kind/release
