Repository 3scale-sre/saas-operator, pull requests merged in 2022-04, with the labels that each got.

#184 Stable release 0.14.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/S, lgtm, approved

#185 feat: improve redis event handling
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  controllers/redisshard_controller.go
  pkg/assets/bindata.go
  pkg/redis/events/message.go
  pkg/redis/events/message_test.go
  pkg/redis/events/watcher.go
  pkg/redis/redis_shard.go
  pkg/redis/redis_shard_test.go
  pkg/version/version.go
Labels: kind/bug, kind/feature, priority/important-soon, size/L, lgtm, approved

#186 feat: Update grafana api
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/test/external-apis/grafanadashboards.integreatly.org.yaml
  pkg/apis/grafana/v1alpha1/grafana_types.go
  pkg/apis/grafana/v1alpha1/grafanadashboard_types.go
  pkg/apis/grafana/v1alpha1/grafanadatasource_types.go
  pkg/apis/grafana/v1alpha1/grafananotificationchannel_types.go
  pkg/apis/grafana/v1alpha1/pluginsList.go
  pkg/apis/grafana/v1alpha1/register.go
  pkg/apis/grafana/v1alpha1/selectors.go
  pkg/apis/grafana/v1alpha1/zz_generated.deepcopy.go
  pkg/generators/common_blocks/grafanadashboard/resource.go
  pkg/reconcilers/basereconciler/v2/resources/simple_resources.go
  pkg/resource_builders/grafanadashboard/resource.go
  pkg/version/version.go
Labels: kind/bug, priority/critical-urgent, size/L, lgtm, approved

#188 Feat/Upgrade ExternalSecret API from v1alpha1 to v1beta1
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/test/external-apis/externalsecrets.external-secrets.io.yaml
  controllers/backend_controller_suite_test.go
  controllers/corsproxy_controller_suite_test.go
  controllers/mappingservice_controller_suite_test.go
  controllers/suite_test.go
  controllers/system_controller_suite_test.go
  controllers/zync_controller_suite_test.go
  main.go
  pkg/apis/externalsecrets/v1beta1/doc.go
  pkg/apis/externalsecrets/v1beta1/externalsecret_types.go
  pkg/apis/externalsecrets/v1beta1/register.go
  pkg/apis/externalsecrets/v1beta1/zz_generated.deepcopy.go
  pkg/generators/common_blocks/pod/externalsecrets.go
  pkg/generators/common_blocks/pod/externalsecrets_test.go
  pkg/reconcilers/basereconciler/v1/reconcile_resources.go
  pkg/reconcilers/basereconciler/v1/test/suite_test.go
  pkg/reconcilers/basereconciler/v1/test/test_controller.go
  pkg/reconcilers/basereconciler/v1/test/test_controller_suite_test.go
  pkg/reconcilers/basereconciler/v2/resources/simple_resources.go
  pkg/reconcilers/basereconciler/v2/test/suite_test.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
  pkg/resource_builders/pod/externalsecrets.go
  pkg/resource_builders/pod/externalsecrets_test.go
  pkg/version/version.go
Labels: needs-kind, needs-priority, size/L, lgtm, approved

#189 release: publish 0.14.2 stable release
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/S, lgtm, approved, kind/release

#190 clean: Update deprecated resource metrics
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/assets/bindata.go
  pkg/assets/dashboards/apicast.json.gtpl
  pkg/assets/dashboards/autossl.json.gtpl
  pkg/assets/dashboards/backend.json.gtpl
  pkg/assets/dashboards/cors-proxy.json.gtpl
  pkg/assets/dashboards/mapping-service.json.gtpl
  pkg/assets/dashboards/system.json.gtpl
  pkg/assets/dashboards/zync.json.gtpl
  pkg/version/version.go
Labels: kind/cleanup, priority/important-soon, size/M, lgtm, approved

#191 clean: remove basereconciler v1 code
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/generators/apicast/config/options.go
  pkg/generators/autossl/config/options.go
  pkg/generators/common_blocks/grafanadashboard/resource.go
  pkg/generators/common_blocks/hpa/resource.go
  pkg/generators/common_blocks/marin3r/util.go
  pkg/generators/common_blocks/marin3r/util_test.go
  pkg/generators/common_blocks/pdb/resource.go
  pkg/generators/common_blocks/pod/environment.go
  pkg/generators/common_blocks/pod/environment_test.go
  pkg/generators/common_blocks/pod/externalsecrets.go
  pkg/generators/common_blocks/pod/externalsecrets_test.go
  pkg/generators/common_blocks/pod/util.go
  pkg/generators/common_blocks/podmonitor/resource.go
  pkg/generators/common_blocks/service/util.go
  pkg/generators/redisshard/statefulset.go
  pkg/generators/sentinel/statefulset.go
  pkg/reconcilers/basereconciler/v1/reconcile_resources.go
  pkg/reconcilers/basereconciler/v1/reconcile_resources_test.go
  pkg/reconcilers/basereconciler/v1/reconciler.go
  pkg/reconcilers/basereconciler/v1/test/api/v1alpha1/example.com_tests.yaml
  pkg/reconcilers/basereconciler/v1/test/api/v1alpha1/test_types.go
  pkg/reconcilers/basereconciler/v1/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/reconcilers/basereconciler/v1/test/suite_test.go
  pkg/reconcilers/basereconciler/v1/test/test_controller.go
  pkg/reconcilers/basereconciler/v1/test/test_controller_suite_test.go
  pkg/reconcilers/basereconciler/v1/types.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/version/version.go
Labels: kind/cleanup, priority/important-longterm, size/XL, lgtm, approved

#192 Feat/Update backend grafana dashboard including optional canary metrics
  pkg/assets/bindata.go
  pkg/assets/dashboards/backend.json.gtpl
Labels: kind/feature, priority/important-soon, size/XXL, lgtm, approved

#193 release: publish v0.14.3 stable release
  Makefile
  README.md
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/S, lgtm, approved, kind/release
