Repository 3scale-sre/saas-operator, pull requests merged in 2022-12, with the labels that each got.

#236 Fix regression introduced by commit 8bc3e0d
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  controllers/twemproxyconfig_controller.go
  pkg/version/version.go
Labels: kind/bug, priority/critical-urgent, size/S, lgtm, approved

#237 Simplify the workload reconciler
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/suite_test.go
  controllers/system_controller.go
  controllers/zync_controller.go
  main.go
  pkg/generators/apicast/generator.go
  pkg/generators/autossl/generator.go
  pkg/generators/backend/generator.go
  pkg/generators/corsproxy/generator.go
  pkg/generators/echoapi/generator.go
  pkg/generators/mappingservice/generator.go
  pkg/generators/system/generator.go
  pkg/generators/zync/generator.go
  pkg/reconcilers/workloads/deployment_based_workload.go
  pkg/reconcilers/workloads/deployment_based_workload_test.go
  pkg/reconcilers/workloads/interfaces.go
  pkg/reconcilers/workloads/resources.go
  pkg/reconcilers/workloads/resources_test.go
  pkg/reconcilers/workloads/test/api/v1alpha1/example.com_tests.yaml
  pkg/reconcilers/workloads/test/api/v1alpha1/test_types.go
  pkg/reconcilers/workloads/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/reconcilers/workloads/test/suite_test.go
  pkg/reconcilers/workloads/test/test_controller.go
  pkg/reconcilers/workloads/test/test_controller_suite_test.go
Labels: kind/feature, priority/important-longterm, size/L, lgtm, approved

#238 fix/template-annotations
  pkg/reconcilers/basereconciler/v2/resources/deployment.go
  pkg/reconcilers/basereconciler/v2/resources/statefulset.go
  pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
Labels: kind/bug, priority/critical-urgent, size/S, lgtm, approved

#227 fix: Update deprecated autoscaling api
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/backend_controller_suite_test.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/system_controller.go
  controllers/system_controller_suite_test.go
  controllers/zync_controller.go
  pkg/reconcilers/basereconciler/v2/reconciler.go
  pkg/reconcilers/basereconciler/v2/resources/hpa.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
  pkg/reconcilers/workloads/resources.go
  pkg/reconcilers/workloads/resources_test.go
  pkg/reconcilers/workloads/test/test_controller.go
  pkg/reconcilers/workloads/test/test_controller_suite_test.go
  pkg/resource_builders/hpa/resource.go
  test/util/assert.go
Labels: kind/feature, priority/important-longterm, size/M, lgtm, approved

#241 release/v0.17.3
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  docs/api-reference/config.yaml
  docs/api-reference/reference.asciidoc
  docs/api-reference/templates/asciidoctor/gv_details.tpl
  docs/api-reference/templates/asciidoctor/gv_list.tpl
  docs/api-reference/templates/asciidoctor/type.tpl
  docs/api-reference/templates/asciidoctor/type_members.tpl
  pkg/version/version.go
Labels: priority/important-soon, size/M, lgtm, approved, kind/release

#242 Fix randomization in parallel ginkgo test runs
  controllers/suite_test.go
  pkg/reconcilers/basereconciler/v2/test/suite_test.go
  pkg/reconcilers/workloads/test/suite_test.go
  test/e2e/suite_test.go
Labels: kind/bug, priority/important-longterm, size/S, lgtm, approved
