Repository 3scale-sre/saas-operator, pull requests merged in 2022-01, with the labels that each got.

#143 Adjust operator resources
  config/default/custom/manager_patch.yaml
Labels: kind/bug, priority/important-soon, size/XS, lgtm, approved

#144 Release v0.12.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  docs/api-reference/reference.asciidoc
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#145 feat/twemproxy-config
  PROJECT
  api/v1alpha1/redisshard_types.go
  api/v1alpha1/sentinel_types.go
  api/v1alpha1/twemproxyconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/saas.3scale.net_redisshards.yaml
  config/crd/bases/saas.3scale.net_sentinels.yaml
  config/crd/bases/saas.3scale.net_twemproxyconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_twemproxyconfigs.yaml
  config/crd/patches/webhook_in_twemproxyconfigs.yaml
  config/rbac/role.yaml
  config/rbac/twemproxyconfig_editor_role.yaml
  config/rbac/twemproxyconfig_viewer_role.yaml
  config/samples/kustomization.yaml
  config/samples/saas_v1alpha1_twemproxyconfig.yaml
  controllers/redisshard_controller.go
  controllers/sentinel_controller.go
  controllers/suite_test.go
  controllers/twemproxyconfig_controller.go
  go.mod
  main.go
  pkg/generators/backend/cron_deployment.go
  pkg/generators/backend/listener_deployment.go
  pkg/generators/backend/worker_deployment.go
  pkg/generators/redisshard/generator.go
  pkg/generators/redisshard/statefulset.go
  pkg/generators/sentinel/services.go
  pkg/generators/twemproxyconfig/configmap.go
  pkg/generators/twemproxyconfig/configmap_test.go
  pkg/generators/twemproxyconfig/generator.go
  pkg/reconcilers/threads/manager.go
  pkg/reconcilers/threads/manager_test.go
  pkg/redis/events/watcher.go
  pkg/redis/metrics/sentinel_metrics.go
  pkg/redis/sentinel.go
  pkg/redis/sentinel_test.go
  pkg/resource_builders/pod/util.go
  pkg/util/k8s.go
Labels: kind/feature, priority/important-soon, size/XL, lgtm, approved

#147 feat: echo-api controller update to workload reconciler
  controllers/echoapi_controller.go
  controllers/echoapi_controller_suite_test.go
  controllers/suite_test.go
  main.go
  pkg/generators/echoapi/deployment.go
  pkg/generators/echoapi/generator.go
  pkg/generators/echoapi/service.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#149 feat/twemproxy-restart-on-failover
  api/v1alpha1/twemproxyconfig_types.go
  config/rbac/role.yaml
  controllers/twemproxyconfig_controller.go
  pkg/generators/twemproxyconfig/generator.go
  pkg/util/error.go
  pkg/util/error_test.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#150 Feat/Add ExternalSecrets to saas-operator
  api/v1alpha1/common_types.go
  api/v1alpha1/common_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_corsproxies.yaml
  config/crd/bases/saas.3scale.net_mappingservices.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_zyncs.yaml
  config/test/external-apis/externalsecrets.external-secrets.io.yaml
  config/test/kustomization.yaml
  controllers/suite_test.go
  main.go
  pkg/apis/externalsecrets/v1alpha1/doc.go
  pkg/apis/externalsecrets/v1alpha1/externalsecret_types.go
  pkg/apis/externalsecrets/v1alpha1/register.go
  pkg/apis/externalsecrets/v1alpha1/zz_generated.deepcopy.go
  pkg/generators/common_blocks/pod/externalsecrets.go
  pkg/generators/common_blocks/pod/externalsecrets_test.go
  pkg/reconcilers/basereconciler/v1/reconcile_resources.go
  pkg/reconcilers/basereconciler/v1/test/suite_test.go
  pkg/reconcilers/basereconciler/v1/test/test_controller.go
  pkg/reconcilers/basereconciler/v1/test/test_controller_suite_test.go
  pkg/reconcilers/basereconciler/v2/resources/simple_resources.go
  pkg/reconcilers/basereconciler/v2/test/suite_test.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
  pkg/reconcilers/workloads/test/suite_test.go
  pkg/reconcilers/workloads/test/test_controller.go
  pkg/reconcilers/workloads/test/test_controller_suite_test.go
  pkg/resource_builders/pod/externalsecrets.go
  pkg/resource_builders/pod/externalsecrets_test.go
Labels: kind/feature, priority/important-soon, size/XL, lgtm, approved

#151 feat: autossl v2 reconciler
  Makefile
  api/v1alpha1/autossl_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/saas.3scale.net_autossls.yaml
  controllers/autossl_controller.go
  controllers/autossl_controller_suite_test.go
  controllers/suite_test.go
  main.go
  pkg/assets/bindata.go
  pkg/generators/autossl/deployment.go
  pkg/generators/autossl/generator.go
  pkg/generators/autossl/service.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#156 feat: fix autossl svc selector
  controllers/autossl_controller_suite_test.go
  pkg/generators/autossl/generator.go
Labels: kind/bug, priority/important-soon, size/M, lgtm, approved

#158 Add a switch to TwemproxyConfig to disable configmap contents reconcile
  api/v1alpha1/twemproxyconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/twemproxyconfig_controller.go
Labels: kind/feature, priority/important-soon, size/S, lgtm, approved

#157 feat: upgrade cors-proxy to v2 workload reconciler
  controllers/corsproxy_controller.go
  controllers/corsproxy_controller_suite_test.go
  controllers/echoapi_controller.go
  controllers/suite_test.go
  main.go
  pkg/generators/corsproxy/config/options.go
  pkg/generators/corsproxy/deployment.go
  pkg/generators/corsproxy/generator.go
  pkg/generators/corsproxy/service.go
  pkg/generators/echoapi/generator.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#159 feat: upgrade mapping-service to v2 workload reconciler
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_autossls.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_corsproxies.yaml
  bundle/manifests/saas.3scale.net_mappingservices.yaml
  bundle/manifests/saas.3scale.net_sentinels.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_twemproxyconfigs.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  config/crd/bases/saas.3scale.net_twemproxyconfigs.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  controllers/mappingservice_controller.go
  controllers/mappingservice_controller_suite_test.go
  controllers/suite_test.go
  main.go
  pkg/assets/bindata.go
  pkg/generators/mappingservice/config/options.go
  pkg/generators/mappingservice/deployment.go
  pkg/generators/mappingservice/generator.go
  pkg/generators/mappingservice/service.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/L, lgtm, approved

#160 Stable release v0.13.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  docs/api-reference/reference.asciidoc
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#161 doc/examples/local-backend-env
  examples/backend/README.md
  examples/backend/backend.yaml
  examples/backend/redis.yaml
  examples/backend/sentinel.yaml
  examples/backend/twemproxyconfig-masters.yaml
  examples/backend/twemproxyconfig-slaves-rw.yaml
  pkg/redis/redis_shard.go
  pkg/redis/redis_shard_test.go
  pkg/redis/sentinel_test.go
Labels: kind/documentation, kind/feature, priority/important-soon, size/M, lgtm, approved

#162 feat: upgrade zync to v2 workload reconciler
  controllers/suite_test.go
  controllers/zync_controller.go
  controllers/zync_controller_suite_test.go
  main.go
  pkg/generators/zync/api_deployment.go
  pkg/generators/zync/config/api_options.go
  pkg/generators/zync/config/que_options.go
  pkg/generators/zync/generator.go
  pkg/generators/zync/que_deployment.go
  pkg/generators/zync/services.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved
