Repository 3scale-sre/saas-operator, pull requests merged in 2022-02, with the labels that each got.

#165 Do not pass the schema as argument to ReconcileOwnedResources
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/redisshard_controller.go
  controllers/sentinel_controller.go
  controllers/zync_controller.go
  pkg/reconcilers/basereconciler/v2/reconciler.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/workloads/test/test_controller.go
Labels: kind/cleanup, priority/important-longterm, size/S, lgtm, approved

#163 feat/apicast/workload-reconciler
  api/v1alpha1/apicast_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/saas.3scale.net_apicasts.yaml
  controllers/apicast_controller.go
  controllers/suite_test.go
  main.go
  pkg/generators/apicast/deployment.go
  pkg/generators/apicast/generator.go
  pkg/generators/apicast/services.go
  pkg/generators/backend/generator.go
Labels: kind/feature, priority/important-longterm, size/M, lgtm, approved

#166 Hardcode the name of the container for all controllers
  pkg/generators/autossl/deployment.go
  pkg/generators/corsproxy/deployment.go
  pkg/generators/echoapi/deployment.go
  pkg/generators/mappingservice/deployment.go
  pkg/generators/zync/api_deployment.go
  pkg/generators/zync/que_deployment.go
Labels: kind/bug, priority/important-soon, size/S, lgtm, approved

#167 Feat/Increase operator memory limit
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/metadata/annotations.yaml
  config/default/custom/manager_patch.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#142 feat: system v2 controller
  .gitignore
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  controllers/autossl_controller.go
  controllers/suite_test.go
  controllers/system_controller.go
  controllers/system_controller_suite_test.go
  main.go
  pkg/assets/bindata.go
  pkg/generators/system/app_deployment.go
  pkg/generators/system/app_service.go
  pkg/generators/system/config/options.go
  pkg/generators/system/config/sphinx_options.go
  pkg/generators/system/console_statefulset.go
  pkg/generators/system/generator.go
  pkg/generators/system/sidekiq_deployment.go
  pkg/generators/system/sphinx_service.go
  pkg/generators/system/sphinx_statefulset.go
  pkg/reconcilers/workloads/resources.go
Labels: kind/feature, priority/important-longterm, size/XL, lgtm, approved

#168 feat: Improved backend testing
  controllers/backend_controller_suite_test.go
  pkg/generators/backend/generator.go
  pkg/generators/backend/listener_deployment.go
  pkg/generators/backend/worker_deployment.go
  pkg/resource_builders/twemproxy/util.go
  pkg/resource_builders/twemproxy/util_test.go
Labels: kind/cleanup, kind/feature, priority/important-longterm, size/L, lgtm, approved

#169 feat: system twemproxy sidecar
  api/v1alpha1/system_types.go
  controllers/system_controller_suite_test.go
  pkg/generators/system/app_deployment.go
  pkg/generators/system/generator.go
  pkg/generators/system/sidekiq_deployment.go
  pkg/resource_builders/twemproxy/options.go
  pkg/resource_builders/twemproxy/util.go
  pkg/resource_builders/twemproxy/util_test.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#176 feat: Improve workload checks
  controllers/suite_test.go
Labels: kind/feature, priority/important-longterm, size/S, lgtm, approved

#172 feat: improve corsproxy tests
  controllers/corsproxy_controller_suite_test.go
Labels: kind/feature, needs-size, priority/important-soon, size/M, lgtm, approved

#173 feat: improve the echo-api tests
  controllers/echoapi_controller_suite_test.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#175 feat: Improve Zync tests
  controllers/zync_controller_suite_test.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#171 feat: autossl improved testing
  controllers/autossl_controller_suite_test.go
  controllers/mappingservice_controller_suite_test.go
Labels: kind/feature, priority/important-soon, size/L, lgtm, approved

#177 feat: improve Apicast tests
  controllers/apicast_controller_suite_test.go
Labels: kind/feature, priority/important-soon, size/L, lgtm, approved

#178 Bug/issue 126 flaky tests
  controllers/apicast_controller_suite_test.go
  controllers/autossl_controller_suite_test.go
  controllers/corsproxy_controller_suite_test.go
  controllers/echoapi_controller_suite_test.go
  controllers/mappingservice_controller_suite_test.go
  controllers/suite_test.go
  controllers/zync_controller_suite_test.go
Labels: kind/bug, priority/important-soon, size/L, lgtm, approved

#179 release: bump version to alpha.2
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  docs/api-reference/reference.asciidoc
  pkg/version/version.go
Labels: kind/feature, priority/important-longterm, size/M, lgtm, approved
