Repository 3scale-sre/saas-operator, pull requests merged in 2022-06, with the labels that each got.

#202 Upgrade controller-runtime and operator-utils
  Makefile
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/redisshard_controller.go
  controllers/sentinel_controller.go
  controllers/suite_test.go
  controllers/system_controller.go
  controllers/zync_controller.go
  go.mod
  go.sum
  main.go
  pkg/generators/base_options.go
  pkg/reconcilers/basereconciler/v2/reconciler.go
  pkg/reconcilers/basereconciler/v2/resources/services.go
  pkg/reconcilers/basereconciler/v2/test/suite_test.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/basereconciler/v2/test/test_controller_suite_test.go
  pkg/reconcilers/workloads/deployment_based_workload.go
  pkg/reconcilers/workloads/test/suite_test.go
Labels: kind/feature, priority/important-soon, size/L, lgtm, approved

#203 Release v0.15.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  docs/api-reference/reference.asciidoc
  pkg/version/version.go
Labels: needs-kind, needs-priority, size/S, lgtm, approved

#204 pdb custom reconciler
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/redisshard_controller.go
  controllers/sentinel_controller.go
  controllers/system_controller.go
  controllers/twemproxyconfig_controller.go
  controllers/zync_controller.go
  pkg/reconcilers/basereconciler/v2/reconciler.go
  pkg/reconcilers/basereconciler/v2/resources/pdb.go
  pkg/reconcilers/basereconciler/v2/resources/services.go
  pkg/reconcilers/basereconciler/v2/resources/simple_resources.go
  pkg/reconcilers/basereconciler/v2/test/test_controller.go
  pkg/reconcilers/workloads/test/test_controller.go
Labels: kind/feature, priority/important-longterm, size/M, lgtm, approved

#207 feat: bump policy api version to v1
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  controllers/apicast_controller.go
  controllers/autossl_controller.go
  controllers/backend_controller.go
  controllers/corsproxy_controller.go
  controllers/echoapi_controller.go
  controllers/mappingservice_controller.go
  controllers/sentinel_controller.go
  controllers/suite_test.go
  controllers/system_controller.go
  controllers/system_controller_suite_test.go
  controllers/zync_controller.go
  pkg/apis/externalsecrets/v1beta1/zz_generated.deepcopy.go
  pkg/apis/grafana/v1alpha1/zz_generated.deepcopy.go
  pkg/assets/bindata.go
  pkg/reconcilers/basereconciler/v2/resources/pdb.go
  pkg/reconcilers/basereconciler/v2/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/reconcilers/workloads/resources.go
  pkg/reconcilers/workloads/resources_test.go
  pkg/reconcilers/workloads/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/reconcilers/workloads/test/test_controller_suite_test.go
  pkg/resource_builders/pdb/resource.go
Labels: kind/feature, priority/important-longterm, size/M, lgtm, approved

#208 Feat/Split sentinel sdown metric
  Makefile
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/apis/externalsecrets/v1beta1/zz_generated.deepcopy.go
  pkg/apis/grafana/v1alpha1/zz_generated.deepcopy.go
  pkg/assets/bindata.go
  pkg/assets/dashboards/redis-sentinel.json.gtpl
  pkg/reconcilers/basereconciler/v2/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/reconcilers/workloads/test/api/v1alpha1/zz_generated.deepcopy.go
  pkg/redis/events/watcher.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/M, lgtm, approved

#211 Delete stale metrics
  examples/backend/redis.yaml
  pkg/redis/metrics/sentinel_metrics.go
Labels: kind/bug, priority/important-soon, size/S, lgtm, approved
