Repository 3scale-sre/saas-operator, pull requests merged in 2023-01, with the labels that each got.

#243 refactor/envoyconfig-generation-api
  Makefile
  api/v1alpha1/marin3r_types.go
  api/v1alpha1/marin3r_types_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_apicasts.yaml
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  config/samples/saas_v1alpha1_echoapi.yaml
  controllers/apicast_controller.go
  controllers/apicast_controller_suite_test.go
  controllers/backend_controller.go
  controllers/backend_controller_suite_test.go
  controllers/echoapi_controller.go
  controllers/echoapi_controller_suite_test.go
  controllers/suite_test.go
  docs/api-reference/reference.asciidoc
  go.mod
  pkg/generators/apicast/generator.go
  pkg/generators/backend/generator.go
  pkg/generators/echoapi/generator.go
  pkg/reconcilers/basereconciler/v2/test/suite_test.go
  pkg/reconcilers/workloads/interfaces.go
  pkg/reconcilers/workloads/resources.go
  pkg/reconcilers/workloads/test/suite_test.go
  pkg/resource_builders/envoyconfig/auto/secrets.go
  pkg/resource_builders/envoyconfig/auto/secrets_test.go
  pkg/resource_builders/envoyconfig/descriptor/interface.go
  pkg/resource_builders/envoyconfig/factory/default.go
  pkg/resource_builders/envoyconfig/factory/factory.go
  pkg/resource_builders/envoyconfig/factory/factory_test.go
  pkg/resource_builders/envoyconfig/resource.go
  pkg/resource_builders/envoyconfig/resource_test.go
  pkg/resource_builders/envoyconfig/templates/clusters.go
  pkg/resource_builders/envoyconfig/templates/clusters_test.go
  pkg/resource_builders/envoyconfig/templates/common_messages.go
  pkg/resource_builders/envoyconfig/templates/listeners.go
  pkg/resource_builders/envoyconfig/templates/listeners_test.go
  pkg/resource_builders/envoyconfig/templates/rawconfig.go
  pkg/resource_builders/envoyconfig/templates/rawconfig_test.go
  pkg/resource_builders/envoyconfig/templates/routeconfigurations.go
  pkg/resource_builders/envoyconfig/templates/routeconfigurations_test.go
  pkg/resource_builders/envoyconfig/templates/runtimes.go
  pkg/resource_builders/envoyconfig/templates/runtimes_test.go
  pkg/version/version.go
  test/e2e/sentinel_suite_test.go
  test/e2e/suite_test.go
Labels: kind/feature, priority/important-soon, size/XL, lgtm, approved

#244 Feat/Add sphinx batch size field to System CR
  api/v1alpha1/system_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  config/crd/bases/saas.3scale.net_apicasts.yaml
  config/crd/bases/saas.3scale.net_backends.yaml
  config/crd/bases/saas.3scale.net_echoapis.yaml
  config/crd/bases/saas.3scale.net_systems.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  docs/api-reference/reference.asciidoc
  pkg/generators/system/config/sphinx_options.go
Labels: kind/feature, priority/important-soon, size/S, lgtm, approved

#246 Fix/System-config secret hash trigger
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/generators/system/generator.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/S, lgtm, approved

#247 Stable release v0.18.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/S, lgtm, approved, kind/release
