Repository 3scale-sre/saas-operator, pull requests merged in 2023-02, with the labels that each got.

#248 Prune EnvoyConfigs
  pkg/reconcilers/basereconciler/v2/reconciler.go
Labels: kind/bug, priority/important-longterm, size/XS, lgtm, approved

#251 Fix/Remove yabeda metrics scrapping from system-app
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/generators/system/generator.go
  pkg/version/version.go
Labels: kind/bug, priority/critical-urgent, size/S, lgtm, approved

#252 Stable release v0.18.1
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/version/version.go
Labels: priority/important-soon, size/S, lgtm, approved, kind/release
