Repository 3scale-sre/saas-operator, pull requests merged in 2024-01, with the labels that each got.

#284 Update graphs on System dashboard
  pkg/assets/dashboards/system.json.gtpl
Labels: needs-kind, needs-priority, size/S, lgtm, approved

#286 Fix sudo in shardedredisbackups
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/redis/backup/s3upload.go
  pkg/ssh/remote_exec.go
  pkg/version/version.go
Labels: kind/bug, priority/important-soon, size/S, lgtm, approved

#288 Feat/Add compatibility with envoy 1.22
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/assets/bindata.go
  pkg/resource_builders/envoyconfig/resource_test.go
  pkg/resource_builders/envoyconfig/templates/listeners.go
  pkg/resource_builders/envoyconfig/templates/listeners_test.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/M, lgtm, approved

#289 New release v0.21.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  docs/api-reference/reference.asciidoc
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: priority/important-soon, size/L, lgtm, approved, kind/release

#290 Feat/Add tls_maximum_protocol_version TLSv1.3 to EnvoyConfig
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  pkg/resource_builders/envoyconfig/resource_test.go
  pkg/resource_builders/envoyconfig/templates/listeners.go
  pkg/resource_builders/envoyconfig/templates/listeners_test.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/S, lgtm, approved

#291 Cleanup/Finally remove system deprecated BACKEND_ROUTE envvar
  Makefile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  pkg/generators/system/config/options.go
  pkg/version/version.go
Labels: kind/cleanup, priority/important-soon, size/S, lgtm, approved

#292 Stable release v0.22.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/kustomization.yaml
  docs/api-reference/reference.asciidoc
  pkg/version/version.go
Labels: priority/important-soon, size/S, lgtm, approved, kind/release
