Repository 3scale-sre/saas-operator, pull requests merged in 2025-05, with the labels that each got.

#316 feat/upgrade-makefile-and-tooling
  .github/workflows/catalog.yaml
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  Dockerfile
  Makefile
  config/local-setup/databases/system-mysql/resources.yaml
  controllers/apicast_controller_suite_test.go
  controllers/autossl_controller_suite_test.go
  controllers/backend_controller_suite_test.go
  controllers/corsproxy_controller_suite_test.go
  controllers/echoapi_controller_suite_test.go
  controllers/mappingservice_controller_suite_test.go
  controllers/redisshard_controller_suite_test.go
  controllers/sentinel_controller_suite_test.go
  controllers/suite_test.go
  controllers/system_controller_suite_test.go
  controllers/zync_controller_suite_test.go
  docs/api-reference/config.yaml
  examples/backend/redis-v4/redis.yaml
  examples/backend/redis-v6/redis.yaml
  hack/apply-kustomize.sh
  main.go
  pkg/assets/bindata.go
  pkg/generators/system/tekton_pipeline.go
  pkg/generators/system/tekton_task.go
  pkg/resource_builders/twemproxy/util.go
  test/assets/redis-with-ssh/Dockerfile
  test/e2e/shardedredisbackup_suite_test.go
  test/util/util.go
Labels: kind/feature, priority/important-longterm, size/L, lgtm, approved, wg/sre

#318 feat/file-based-catalog
  .github/workflows/catalog.yaml
  Makefile
  PROJECT
  bundle.Dockerfile
  bundle/manifests/saas-operator.clusterserviceversion.yaml
  bundle/manifests/saas.3scale.net_apicasts.yaml
  bundle/manifests/saas.3scale.net_autossls.yaml
  bundle/manifests/saas.3scale.net_backends.yaml
  bundle/manifests/saas.3scale.net_corsproxies.yaml
  bundle/manifests/saas.3scale.net_echoapis.yaml
  bundle/manifests/saas.3scale.net_mappingservices.yaml
  bundle/manifests/saas.3scale.net_redisshards.yaml
  bundle/manifests/saas.3scale.net_sentinels.yaml
  bundle/manifests/saas.3scale.net_shardedredisbackups.yaml
  bundle/manifests/saas.3scale.net_systems.yaml
  bundle/manifests/saas.3scale.net_twemproxyconfigs.yaml
  bundle/manifests/saas.3scale.net_zyncs.yaml
  bundle/metadata/annotations.yaml
  catalog/saas-operator.Dockerfile
  catalog/saas-operator/alpha-channel.yaml
  catalog/saas-operator/objects/marin3r.v0.25.0.clusterserviceversion.yaml
  catalog/saas-operator/objects/marin3r.v0.25.1.clusterserviceversion.yaml
  catalog/saas-operator/objects/saas-operator.v0.26.0-alpha.1.clusterserviceversion.yaml
  catalog/saas-operator/operator.yaml
  catalog/saas-operator/stable-channel.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/saas-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  pkg/assets/bindata.go
  pkg/version/version.go
Labels: kind/feature, priority/important-soon, size/XL, lgtm, approved, wg/sre

#323 Add prometheus PodMonitor to mt-ingress local-setup
  config/local-setup/workloads/mt-ingress.yaml
Labels: kind/feature, priority/important-soon, size/S, lgtm, approved, wg/sre

#324 Feat/local-setup envoy improvements
  config/local-setup/workloads/apicast.yaml
  config/local-setup/workloads/mt-ingress.yaml
Labels: kind/feature, priority/important-soon, size/S, lgtm, approved, wg/sre
